// Assets
import evolutionHeader from '../app/assets/evolution-header.jpg';
import evolutionOld from '../app/assets/evolution-old-home.jpg';
import evolutionOldMobile from '../app/assets/evolution-old-home-mobile.jpg';
import evolutionAtomic from '../app/assets/evolution-atomic.jpg';
import evolutionAtomicMobile from '../app/assets/evolution-atomic-mobile.jpg';
import evolutionProcess from '../app/assets/evolution-process.jpg';
import evolutionWC from '../app/assets/evolution-wc.jpg';
import evolutionWCMobile from '../app/assets/evolution-wc-mobile.jpg';
import evolutionNew from '../app/assets/evolution-new-home.jpg';
import evolutionNewMobile from '../app/assets/evolution-new-home-mobile.jpg';
import evolutionConference from '../app/assets/evolution-conference.jpg';
import evolutionDesignTokensDesktop from '../app/assets/evolution-design-tokens-desktop.png';
import evolutionDesignTokensMobile from '../app/assets/evolution-design-tokens-mobile.png';
import evolutionWorkshopDesktop from '../app/assets/evolution-workshop-desktop.png';
import evolutionWorkshopMobile from '../app/assets/evolution-workshop-mobile.png';
import evoluutionTechStackDesktop from '../app/assets/evolution-tech-stack-desktop.png';
import evoluutionTechStackMobile from '../app/assets/evolution-tech-stack-mobile.png';
import evolutionNewHomepage from '../app/assets/evolution-new-homepage.png';